import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import projects from './projects.json' with {type:'json'};
import {renderHome,renderProject} from './templates.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const arg=(name,fallback)=>process.argv.find(s=>s.startsWith('--'+name+'='))?.split('=').slice(1).join('=')||fallback;
const preview=process.argv.includes('--preview');
const origin=arg('origin','https://mohamed-almotaz.pages.dev').replace(/\/$/,'');
const out=path.resolve(root,arg('out','dist'));
const sharp=(await import(process.env.PORTFOLIO_SHARP_PATH?pathToFileURL(process.env.PORTFOLIO_SHARP_PATH).href:'sharp')).default;
await fs.mkdir(path.join(out,'media'),{recursive:true});
const files=[...new Set(projects.flatMap(p=>[...p.images,p.cover,p.logo,...p.screens.map(s=>s.image),...(p.marketing||[]).map(s=>s.image)].filter(Boolean)))];files.push('cv-preview.png','personal-wordmark-v2.png');
const media={};
await sharp(path.join(root,'favicon.svg')).resize(180,180).png().toFile(path.join(out,'media','personal-icon.png'));
for(const name of files){const file=name.replace(/\.(png|jpg|jpeg)$/i,'.webp');const result=await sharp(path.join(root,name)).resize({width:1600,withoutEnlargement:true}).webp({quality:86,effort:5}).toFile(path.join(out,'media',file));media[name]={file,width:result.width,height:result.height,bytes:result.size};}
for(const name of ['style.css','favicon.svg','portfolio-sans.woff2','portfolio-sans-bold.woff2','FONT_LICENSE.txt','IBMPlexSansArabic-Regular.woff2','IBMPlexSansArabic-Medium.woff2','IBMPlexSansArabic-SemiBold.woff2','IBM_PLEX_FONT_LICENSE.txt','Mohamed_Almotaz_CV.pdf','Mohamed_Almotaz_Nursing_CV.pdf','Mohamed_Almotaz_Design_Tech_CV.pdf'])await fs.copyFile(path.join(root,name),path.join(out,name));
await fs.copyFile(path.join(root,'enhancements.js'),path.join(out,'app.js'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[];
function page(language,project=null){
 const ar=language==='ar',tr=(en,arabic)=>ar?arabic:en;
 const route=(ar?'ar/':'')+(project?'work/'+project.slug+'/':'');
 const other=(!ar?'ar/':'')+(project?'work/'+project.slug+'/':'');
 const prefix='../'.repeat(route.split('/').filter(Boolean).length),home=prefix+(ar?'ar/':'');
 const t=project?(ar?{...project,...project.ar}:project):null;
 const title=project?t.title+' - Mohamed Almotaz':tr('Mohamed Almotaz - Visual Design & Digital Products','محمد المعتز - تصميم بصري ومنتجات رقمية');
 const description=project?t.description:tr('Visual design, useful digital products and course operations by Mohamed Almotaz. Explore 12 projects and professional experience.','أعمال محمد المعتز في التصميم البصري والمنتجات الرقمية وإدارة الكورسات. استكشف 12 مشروعًا والسيرة الذاتية.');
 let body=project?renderProject(project,language,prefix,media):renderHome(language,prefix,media);
 for(const [name,m] of Object.entries(media))body=body.replaceAll('data-image="'+name+'"','data-image="'+prefix+'media/'+m.file+'"');
 if(project&&['pinkcare','gvhd','pflegekompass'].includes(project.id))body=body.replace('</div></section><div class="case-hero',`<p class="prototype-note">${tr('Educational or interface prototype; clinical validation and use in patient care have not been established.','نموذج تثقيفي أو نموذج واجهة؛ لم يثبت اعتماد طبي أو استخدام في رعاية المرضى.')}</p></div></section><div class="case-hero`);
 const en=origin+'/'+(project?'work/'+project.slug+'/':''),arabic=origin+'/ar/'+(project?'work/'+project.slug+'/':'');
 const schema=JSON.stringify(project?{'@context':'https://schema.org','@type':'CreativeWork',name:t.title,description:t.description,url:origin+'/'+route,creator:{'@type':'Person',name:'Mohamed Almotaz'},inLanguage:language}:{'@context':'https://schema.org','@type':'Person',name:'Mohamed Almotaz',url:origin+'/',jobTitle:'Visual Designer and Digital Operations Coordinator',sameAs:['https://github.com/Mohamedmotaz','https://www.linkedin.com/in/mohamed-almotaz-ballah-4559a1189/']}).replace(/</g,'\\u003c');
 const html=`<!doctype html><html lang="${language}" dir="${ar?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${preview?'noindex,nofollow':'index,follow'}"><meta name="theme-color" content="#f8f7f3"><link rel="canonical" href="${origin}/${route}"><link rel="alternate" hreflang="en" href="${en}"><link rel="alternate" hreflang="ar" href="${arabic}"><link rel="alternate" hreflang="x-default" href="${en}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}/${route}"><meta property="og:type" content="${project?'article':'website'}"><meta property="og:image" content="${origin}/media/${media[project?.cover||'shift-calendar-clean.png'].file}"><link rel="icon" href="${prefix}favicon.svg"><link rel="stylesheet" href="${prefix}style.css"><script src="${prefix}app.js" defer></script><script type="application/ld+json">${schema}</script></head><body><a class="skip" href="#main">${tr('Skip to content','انتقل للمحتوى')}</a><header><a href="${home||'./'}" class="wordmark">MOHAMED<br>ALMOTAZ</a><nav aria-label="${tr('Main navigation','التنقل الرئيسي')}"><a href="${home}#work">${tr('Work','الأعمال')}</a><a href="${home}#about">${tr('About','عنّي')}</a><a href="${home}#cv">${tr('CV','السيرة الذاتية')}</a><a href="${home}#contact">${tr('Let’s talk ↗','نتكلم ↖')}</a><a id="language" href="${prefix+other||'./'}" lang="${ar?'en':'ar'}" hreflang="${ar?'en':'ar'}">${tr('العربية','English')}</a><details class="mobile-menu"><summary>${tr('Menu','القائمة')}</summary><div><a href="${home}#about">${tr('About me','عنّي')}</a><a href="${home}#approach">${tr('How I work','طريقة شغلي')}</a><a href="${home}#nursing">${tr('Nursing experience','خبرة التمريض')}</a><a href="${home}#cv">${tr('CVs','السيرة الذاتية')}</a><a href="${home}#contact">${tr('Contact','تواصل')}</a></div></details></nav></header><main id="main">${body}</main><footer><span>© 2026 Mohamed Almotaz${preview?tr(' · Review preview',' · معاينة المراجعة'):''}</span><a class="wordmark" href="${home||'./'}">MOHAMED ALMOTAZ.</a><span>${tr('Visual design · Digital products · Cairo','تصميم بصري · منتجات رقمية · القاهرة')}</span><a href="mailto:mohamedmotaz189@gmail.com">${tr('Email ↗','البريد ↖')}</a></footer><dialog id="viewer" aria-label="${tr('Image viewer','عارض الصور')}"><button id="close-viewer" aria-label="${tr('Close image','إغلاق الصورة')}">×</button><p></p></dialog></body></html>`;
 const branded=html.replace('<link rel="icon" href="'+prefix+'favicon.svg">','<link rel="icon" type="image/png" href="'+prefix+'media/personal-icon.png"><link rel="apple-touch-icon" href="'+prefix+'media/personal-icon.png">').replace('class="wordmark">MOHAMED<br>ALMOTAZ','class="wordmark personal-brand" aria-label="Mohamed Almotaz"><img src="'+prefix+'media/personal-wordmark-v2.webp" width="2172" height="724" alt="Mohamed Almotaz">');
 return {route,html:branded};
}
for(const language of ['en','ar'])for(const p of [null,...projects]){const {route,html}=page(language,p);await fs.mkdir(path.join(out,route),{recursive:true});await fs.writeFile(path.join(out,route,'index.html'),html);routes.push(route);}
await fs.writeFile(path.join(out,'robots.txt'),preview?'User-agent: *\nDisallow: /\n':'User-agent: *\nAllow: /\nSitemap: '+origin+'/sitemap.xml\n');
await fs.writeFile(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(route=>'<url><loc>'+origin+'/'+route+'</loc></url>').join('')+'</urlset>');
await fs.writeFile(path.join(out,'_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Cache-Control: public, max-age=0, must-revalidate\n'+(preview?'  X-Robots-Tag: noindex, nofollow\n':'')+'/media/*\n  Cache-Control: public, max-age=86400\n');
await fs.writeFile(path.join(out,'_redirects'),'/index.html / 301\n/ar/index.html /ar/ 301\n');
await fs.writeFile(path.join(out,'404.html'),'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><title>Page not found - Mohamed Almotaz</title><link rel="icon" href="/media/personal-icon.png"><link rel="stylesheet" href="/style.css"></head><body><header><a href="/" class="personal-brand" aria-label="Mohamed Almotaz"><img src="/media/personal-wordmark-v2.webp" width="2172" height="724" alt="Mohamed Almotaz"></a><a href="/ar/" lang="ar">العربية ↗</a></header><main class="wrap not-found"><span class="eyebrow">404 / PAGE NOT FOUND</span><h1>Let’s get you<br>back to the work.</h1><p>This page is unavailable. Explore the portfolio or get in touch with Mohamed.</p><p lang="ar" dir="rtl">الصفحة غير متاحة. يمكنك الرجوع للأعمال أو التواصل مع محمد.</p><div class="links"><a href="/">Explore the portfolio ↗</a><a href="/ar/" lang="ar">استكشف الأعمال ↖</a><a href="mailto:mohamedmotaz189@gmail.com">Get in touch ↗</a></div></main></body></html>');
await fs.writeFile(path.join(root,'media-manifest.json'),JSON.stringify(media,null,2)+'\n');
console.log(JSON.stringify({output:out,preview,origin,htmlPages:routes.length,images:files.length,mediaBytes:Object.values(media).reduce((a,m)=>a+m.bytes,0)},null,2));
